<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageId>Tabic.Core</PackageId>
    <Authors>DrMelt</Authors>
    <Description>Core library for Tabic application</Description>
  </PropertyGroup>

</Project>
